# Generated by Django 5.0.1 on 2025-01-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='asignada_a',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='creada_por',
        ),
    ]
